version: "3.9"

services:
  keycloak:
    image: "quay.io/keycloak/keycloak:16.1.0"
    networks:
      - intranet
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  mailslurper:
    build: mailslurper
    restart: always
    networks:
      - intranet
    ports:
      - "2500:2500"
      - "8081:8081"
      - "8085:8085"
  frontend:
    depends_on:
      - keycloak
    build: frontend
    ports:
      - "8964:3000"

networks:
  intranet: